# Generated by Django 6.0.4 on 2026-05-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='descripcion_tienda',
            field=models.TextField(blank=True, help_text='Cuéntanos sobre tu tienda'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='pendiente', max_length=20),
        ),
    ]
